ERROR: '@Jekyll::GitHubMetadata::EditLinkTag#parts' is not allowed
Liquid Exception: '@Jekyll::GitHubMetadata::EditLinkTag#parts' is not allowed as an instance variable name in /_layouts/default.liquid

caused by {% github_edit_link %} in _includes/templates/breadcrumbs.liquid 30